{{ config(materialized='external', location='data/gold/mart_company_quarterly_metrics.parquet') }}

select
    company_quarter_key,
    company_id,
    ticker,
    company_name,
    sector,
    industry,
    country,
    fiscal_quarter,
    fiscal_quarter_start_date,
    revenue,
    previous_quarter_revenue,
    revenue_growth_qoq,
    gross_profit,
    operating_income,
    net_income,
    total_assets,
    total_liabilities,
    equity,
    operating_cash_flow,
    gross_margin,
    operating_margin,
    net_margin,
    debt_to_equity,
    return_on_assets,
    cash_flow_margin,
    asset_turnover,
    average_close_price,
    quarter_high_close_price,
    quarter_low_close_price,
    quarter_end_close_price,
    average_daily_return,
    average_volume,
    average_moving_average_20d,
    average_rolling_volatility_20d,
    total_liabilities / nullif(total_assets, 0) as liabilities_to_assets
from {{ ref('int_company_quarterly_features') }}
